### ISSUE TITLE
Move documentation to RTD

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.testing#20]
Currently the documentation is only in the repository. It is not well readable because the files have a `.txt` extension instead of `.rst`.

**Comment by icemac** [comment]
There is already https://zopetesting.readthedocs.io/en/latest/ but it only contains an overview of the modules provided here.
Maybe the doctests should also be rendered over there.

**Comment by jamadden** [comment]
The URL zopetesting.readthedocs.io is owned by @tseaver but is in need of maintenance. For example, there is no webhook installed here to updated the docs, and they haven't been built in 3 years. Perhaps @tseaver would be willing to add some co-maintainers?

**Comment by tseaver** [comment]
I've lost any idea about how the docs should be built here.  There is no `docs/` directory, and the `rtd.txt` file looks like it is just a set of prereqs.  The [latest](https://readthedocs.org/projects/zopetesting/builds/14664125/) and [stable](https://readthedocs.org/projects/zopetesting/builds/14664126/) builds on RTD are failing.

I would be happy to add one or more owners who are motivated to fix the docs build.

**Comment by icemac** [comment]
@tseaver Could you please add me (`icemac`) and @jamadden (`jamadden@gmail.com`) as co-maintainers at https://readthedocs.org/projects/zopetesting/?

**Comment by tseaver** [comment]
![Screenshot from 2021-09-24 10-16-53](https://user-images.githubusercontent.com/242750/134689722-cee41fe2-a848-4302-b10f-94eedc597c62.png)

**Comment by jamadden** [comment]
Thanks @tseaver! There are a few other zopefoundation projects on RTD that are only maintained by you; when you have the time and motivation if you could add us as maintainers to those it would be appreciated!

In the meantime, I've established the webhook for this project, but it's going to take some TLC to get the docs building again. I'm happy to work on that today.

**Comment by tseaver** [comment]
@jamadden, @icemac I think I've added you both to all the ZF projects for which I was the "last maintainer standing" on RTD.

**Comment by jamadden** [comment]
Thanks @tseaver!
